/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_NdkHello */

#ifndef _Included_com_jni_NdkHello
#define _Included_com_jni_NdkHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_NdkHello
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_NdkHello_getHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
